version: '3'

services:
  lflbsite:
    build:
      context: .
      dockerfile: Dockerfile
    # user: "${UID}:{GID}"  # 👈 Run container as lflbsign user
    labels:
      - traefik.enable=true
      - traefik.http.routers.lflbsite.rule=Host(`lflbsite.webfoundry.dev`)
      - traefik.http.routers.lflbsite.entrypoints=web
      - traefik.http.services.lflbsite.loadbalancer.server.port=80
    ports:
      #  - '${APP_PORT:-80}:80'
      - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
    environment:
      WEBROOT: '/var/www/html/public' 
    volumes:
      - .:/var/www/html
      - /home/lflbsign/lflbassets:/var/www/html/lflbassets
    networks:
      - traefik

networks:
  traefik:
    external: true
